"""add heisenberg fields to signatures

Revision ID: bf27772e96e6
Revises: 1a6018f4f155
Create Date: 2026-01-13 21:44:20.376873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf27772e96e6'
down_revision: Union[str, Sequence[str], None] = '1a6018f4f155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signatures', sa.Column('heisenberg_r', sa.String(), nullable=False))
    op.add_column('signatures', sa.Column('heisenberg_z', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signatures', 'heisenberg_z')
    op.drop_column('signatures', 'heisenberg_r')
    # ### end Alembic commands ###
